services:
  app:
    build:
      context: ./docker/php
    container_name: boilerplate_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: boilerplate_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: boilerplate_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: boilerplate_phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret
    depends_on:
      - db
    networks:
      - laravel


networks:
  laravel:

volumes:
  dbdata:
